### ISSUE TITLE
1.0 release ?

### ISSUE THREAD

**Issue by kdubuc** [akrabat/ip-address-middleware#10]
Hi ! Is there a roadmap to reach 1.0 release ?

**Comment by akrabat** [comment]
The main thing will be support for PSR-15 middleware when it's approved.

**Comment by kdubuc** [comment]
PSR15 vote is sheduled early January http://blog.zend.com/2017/12/21/zend-framework-in-2017-by-the-numbers
Wait and see ! 😉

**Comment by harikt** [comment]
Hope this https://github.com/akrabat/rka-ip-address-middleware/pull/11 will help to move forward ;) .

**Comment by akrabat** [comment]
1.0 released! https://github.com/akrabat/ip-address-middleware/releases/tag/1.0

Note that the new name is `akrabat/ip-address-middleware`
