### ISSUE TITLE
headersToInspect for CloudFlare driven sites

### ISSUE THREAD

**Issue by lord-alfred** [akrabat/ip-address-middleware#18]
https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-
+
https://stackoverflow.com/questions/17540715/using-curl-i-added-the-header-http-x-real-ip-on-the-server-side-it-becomes-h

And I dont know, but current order in `$headersToInspect` maybe wrong.

**Comment by akrabat** [comment]
I'm unclear what problem you have and what the proposed solution is.

**Comment by akrabat** [comment]
Can you propose a specific thing that you want me to change that will solve your problem?

**Comment by lord-alfred** [comment]
If you use the wrong order of headers, then the first will be taken incorrect value for such sites (cloudflare driven).

**Comment by lord-alfred** [comment]
I use this order of headers:
```php
        'CF-Connecting-IP',
        'True-Client-IP',
        'X-Real-IP',
        'Forwarded',
        'X-Forwarded-For',
        'X-Forwarded',
        'X-Cluster-Client-Ip',
        'Client-Ip',
```

**Comment by akrabat** [comment]
Thanks!
