### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by acelaya** [akrabat/ip-address-middleware#26]
Hey!

Would you consider adding PHP 8 support? If so, I'm open for the contribution.

**Comment by akrabat** [comment]
Definitely!

**Comment by acelaya** [comment]
I see the project supports PHP versions since 7.0, and the travis builds are run for v7.0 to v7.2

I would personally bump the minimum supported version to 7.2 at least, but since this is a pretty small project, do you want to continue supporting v7.0 and 7.1 too? I think it's just a matter of adding more phpunit versions.

**Comment by akrabat** [comment]
I'm happy for the next version to be PHP 7.2 or 7.3 through PHP 8. I'll put out a new major version for this, so we can do this.

**Comment by acelaya** [comment]
I have added these two dev dependencies, in order to support PHP `^7.2 || ^8.0`

```
"laminas/laminas-diactoros": "^2.4",
"phpunit/phpunit": "^8.5.8 || ^9.4",
```

If you don't want to support PHP 7.2, then it can be set as this:

```
"laminas/laminas-diactoros": "^2.5",
"phpunit/phpunit": "^9.4",
```

The build is now running with the former. Let's see how it goes (I just tested it locally with PHP 8)

**Comment by acelaya** [comment]
BTW, the build is taking ages because it's running on travis-ci.org, which is getting decomission by the end of the year (or so. Not really sure right now).

You might want to migrate to travis-ci.com or github actions.

**Comment by acelaya** [comment]
The build seems to be passing, supporting PHP 7.2 onwards.
