### ISSUE TITLE
Checks only the first trustedWildcard

### ISSUE THREAD

**Issue by Seagull-4auKa** [akrabat/ip-address-middleware#31]
https://github.com/akrabat/ip-address-middleware/blob/90c38ef95d46c59e12eea236a4d592c03889bbaa/src/IpAddress.php#L195-L206
If first proxy from `trustedWildcard` does not match, `break 2;` exits two cycles instead of one. Thus ignoring the rest of the wildcard list

**Comment by akrabat** [comment]
Thanks @Seagull-4auKa. Fixed in version 2.1.0
