### ISSUE TITLE
second Parameter of __invoke should be RequestHandlerInterface instance 

### ISSUE THREAD

**Issue by manhhoangfnq** [akrabat/ip-address-middleware#41]
```
public function __invoke(ServerRequestInterface $request, ResponseInterface $response, $next)`
    {
        if (!$next) {
            return $response;
        }

        $ipAddress = $this->determineClientIpAddress($request);
        $request = $request->withAttribute($this->attributeName, $ipAddress);

        return $response = $next($request, $response);
  }
```

    
I got the error exception. 

[FATAL] RKA\Middleware\IpAddress::__invoke(): Argument # 2 ($response) must be of type Psr\Http\Message\ResponseInterface, Psr\Http\Server\RequestHandlerInterface@anonymous given, called in /vendor/slim/slim/Slim/MiddlewareDispatcher.php on line 168

**Comment by akrabat** [comment]
How are you calling the middleware? If you are using PSR-15, then you should be using `process()`, not `__invoke()`.
