### ISSUE TITLE
Deprecation warning with PHP 8.4

### ISSUE THREAD

**Issue by acelaya** [akrabat/ip-address-middleware#46]
I have identified this deprecation warning thrown when using with PHP 8.4 `RKA\Middleware\IpAddress::__construct(): Implicitly marking parameter $trustedProxies as nullable is deprecated, the explicit nullable type must be used instead`.

This is the RFC where this was proposed https://wiki.php.net/rfc/deprecate-implicitly-nullable-types

The solution implies implicitly marking parameters as nullable when they have `null` as default value.

I'm happy to provide a PR addressing these warnings and adding PHP 8.4 to the pipeline.

**Comment by akrabat** [comment]
Thanks for the report and fix. Not sure why you deleted your PR so quickly, but I remade and released 2.4.0.

**Comment by acelaya** [comment]
> Not sure why you deleted your PR so quickly

Oh! Sorry, that was unintentional. I think I deleted the source branch from my fork by mistake.

Thanks for the release!
