### ISSUE TITLE
Plugin does not seem to work with current Slim version

### ISSUE THREAD

**Issue by rootuser** [akrabat/ip-address-middleware#5]
Hi,

the usage example you are giving does not seem to work with current Slim 3 versions.

The line:

> $app->add(new RKA\Middleware\IpAddress($checkProxyHeaders, $trustedProxies));

produces the following error:
Argument 1 passed to Slim\Slim::add() must be an instance of Slim\Middleware, instance of RKA\Middleware\IpAddress given

What can I do to use your middleware anyway?

Thank you very much
Kind regards,
Tom

**Comment by akrabat** [comment]
`\Slim\Slim` is Slim 2, not 3.
