### ISSUE TITLE
Doesn't work on AWS using the request object to get headers

### ISSUE THREAD

**Issue by gracedigital** [akrabat/ip-address-middleware#7]
The current code uses the request object to get the headers.
On AWS Elastic Beanstalk for example the request headers are:
    Host: subdomain.domain.com
    HTTP_ACCEPT: application/json
    HTTP_ACCEPT_ENCODING: gzip, deflate
    HTTP_CACHE_CONTROL: no-cache
    CONTENT_TYPE: application/json
    HTTP_POSTMAN_TOKEN: f37b1651-c782-4f29-9f00-e9e1f074a257
    HTTP_USER_AGENT: PostmanRuntime/3.0.11-hotfix.2
    HTTP_X_FORWARDED_FOR: 72.206.90.181
    HTTP_X_FORWARDED_PORT: 80
    HTTP_X_FORWARDED_PROTO: http
    HTTP_CONNECTION: keep-alive

The change I employed was to use the PHP function getallheaders() which provides these headers:
    host: subdomain.domain .com
    Accept: application/json
    accept-encoding: gzip, deflate
    cache-control: no-cache
    Content-Type: application/json
    Postman-Token: 0facf6eb-9d64-4d2f-a9d7-3eaf287bf729
    User-Agent: PostmanRuntime/3.0.11-hotfix.2
    X-Forwarded-For: 72.206.90.181
    X-Forwarded-Port: 80
    X-Forwarded-Proto: http
    Connection: keep-alive

**Comment by conrad10781** [comment]
I've not had this issue while using AWS via an ELB to an EC2 instance, which I believe is what ultimately the Elastic Beanstalk is doing. If this is causing an actual issue, you can utilize the 4th parameter of the constructor ( https://github.com/akrabat/rka-ip-address-middleware/blob/master/src/IpAddress.php#L57 ) until the header is in source itself. Provided you don't want to fork the code.

**Comment by akrabat** [comment]
Using the `headersToInspect` parameter is the way forward here.
